### ISSUE TITLE
test issue

### ISSUE THREAD

**Issue by tanacchi** [H28-CIRKIT-ARC-1stGrade/ROS_lesson#1]
issueのテストです
あくまで先輩の迷惑にならんところでＧｉｔの練習するために立ち上げたグループだから
このグループで何しようが誰も文句言わないさー
ＨＡＨＡＨＡＨＡＨＡ
まだ３人しかいなくて寂しい

**Comment by forno** [comment]
@tanacchi 
寂しいなら私も追加していいのよ(違)

ご存知ないかもしれませんが、CIR-KIT全体に関わるIssueの場が欲しいとの要望があるので、CIR-KITに突如としてRepositoryを作成し、全体用Issue立てましたとかやっていいのよー。
いろいろ試してみてくださいまし。
取り返しのつかないことは無いはずです。えー…ネットにばらしちゃいけない情報を流す以外は。

ではでは。
